name: Deploy to GitHub Pages # 工作流程的名稱

on:
  push:
    branches:
      - main # 當有新的程式碼推送到 'main' 分支時觸發此工作流程
              # 如果您的主分支名稱是 'master'，請將此處改為 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 在 Ubuntu 系統上運行此工作
    permissions:
      contents: write # 允許寫入儲存庫內容
      pages: write    # 允許寫入 GitHub Pages
      id-token: write # 允許獲取 ID 令牌，用於身份驗證

    steps:
      - name: Checkout repository # 步驟1：將儲存庫程式碼複製到工作環境
        uses: actions/checkout@v4

      - name: Setup Pages # 步驟2：設定 GitHub Pages 環境
        uses: actions/configure-pages@v5

      - name: Upload artifact # 步驟3：上傳要部署的檔案
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # 指定要上傳的檔案路徑。'.' 表示上傳儲存庫根目錄下的所有檔案。
                    # 如果您的 index.html 在子資料夾中 (例如 'my-site/')，
                    # 請將此處改為 'my-site/'

      - name: Deploy to GitHub Pages # 步驟4：將上傳的檔案部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        Add GitHub Pages deployment workflow
